import { createSlice } from '@reduxjs/toolkit';
import { deleteAllusers } from '../actions';
// a function that accepts name, initial state and reducers
const userSlice = createSlice({
    name: "users",
    initialState: [],
    reducers: {
        addUser(state, action) {
            state.push(action.payload)
        },
        removeUser(state, action) {
            state.splice(action.payload,1)
         },
        // deleteUsers(state, action) {
        //     return []
        //  },
    },
    extraReducers(builder) {
        builder.addCase(userSlice.actions.deleteUsers, () => {
            return []
        })
    }
});

// This exports the reducer function generated by createSlice.This reducer will be used in the Redux store.
export default userSlice.reducer;
// export const { addUser } = userSlice.actions: This exports the addUser action creator, making it available for dispatching in your application.
export const {addUser,removeUser} = userSlice.actions