import { createSlice } from '@reduxjs/toolkit';
// a function that accepts name, initial state and reducers
const userSlice = createSlice({
    name: "users",
    initialState: [],
    reducers: {
        addUser(state, action) {
            state.push(action.payload)
        },
        removeUser(state, action) {
            state.splice(action.payload,1)
         },
        deleteUsers(state, action) {
            return []
         },
    },
});

// This exports the reducer function generated by createSlice.This reducer will be used in the Redux store.
export default userSlice.reducer;
// export const { addUser } = userSlice.actions: This exports the addUser action creator, making it available for dispatching in your application.
export const {addUser,removeUser,deleteUsers} = userSlice.actions